### PR TITLE
Add .nupkg extension

### PR DESCRIPTION
**Pull request by ChrisMissal**
Requirement for https://github.com/atom/archive-view/pull/28

### CODE REVIEW

**Comment by ChrisMissal** [comment]
This passes on node v0.10, but fails on v0.11 with: 

    $ nvm install 0.11
    Version '0.11' not found - try `nvm ls-remote` to browse available versions.
    The command "nvm install 0.11" failed and exited with 3 during .

I have a suspicion this isn't related to my PR :\

**Comment by ChrisMissal** [comment]
I ran the same build over here: https://travis-ci.org/ChrisMissal/node-ls-archive/builds/76310805 and it passed.

**Comment by kevinsawicki** [comment]
> This passes on node v0.10, but fails on v0.11 with:

Yeah, node 0.11 shouldn't be used by the build anymore, I'll remove it.

**Comment by kevinsawicki** [comment]
Thanks for adding this

**Pull request merged**
